version: '3.7'
services:
  serverless:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/repo
    command: tail -f /dev/null
    working_dir: /var/repo
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

