version: '3.7'
services:
  serverless:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/repo
      - gem:/usr/local/bundle
      - node:/var/repo/node_modules
    command: tail -f /dev/null
    working_dir: /var/repo
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

volumes:
  gem:
    driver: 'local'
  node:
    driver: 'local'
