service: ruby-node-test

frameworkVersion: '3'

provider:
  name: aws
  runtime: ruby2.7
  region: ap-northeast-1
  stage: dev

plugins:
  - serverless-prune-plugin
  - serverless-ruby-layer

custom:
  prune:
    automatic: true
    number: 3
    includeLayers: true
  rubyLayer:
    include_functions:
      - httparty

functions:
  hello:
    handler: handler.hello
    description: Simple Hello, World
  httparty:
    handler: libs/httparty.hello
    description: Use Gem

package:
  exclude:
    - .env
    - .git
    - .gitignore
    - Dockerfile
    - docker-compose.yml
