service: ruby-node-test

frameworkVersion: '3'

provider:
  name: aws
  runtime: ruby2.7
  region: ap-northeast-1
  stage: ${opt.stage, self:custom.defaultStage}

plugins:
  - serverless-prune-plugin
  - serverless-ruby-layer

custom:
  defaultStage: dev
  prune:
    automatic: true
    includeLayers: true
    number: 3
  rubyLayer:
    include_functions:
      - httparty

functions:
  hello:
    handler: handler.hello
  httparty:
    handler: libs/httparty.hello

