service: ruby-node-test

frameworkVersion: '3'

provider:
  name: aws
  runtime: ruby2.7
  memorySize: 128
  region: ap-northeast-1
  stage: dev

plugins:
  - serverless-prune-plugin
  - serverless-ruby-layer

package:
  individually: true
  patterns:
    - '!./**'

custom:
  prune:
    automatic: true
    number: 3
    includeLayers: true
  rubyLayer:
    include_functions:
      - httparty

functions:
  hello:
    handler: functions/hello_world.handler
    description: Simple Hello, World
    package:
      patterns:
        - "functions/hello_world.rb"
  httparty:
    handler: functions/httparty.handler
    description: change description (using gem)
    package:
      patterns:
        - "functions/httparty.rb"
